/* config.h. Generated by CMake for sdformat8. */

/* Protocol version */
#define SDF_PROTOCOL_VERSION "1.6"
/* \deprecated SDF_VERSION is deprecated. Please
 * use SDF_PROTOCOL_VERSION or SDF_PKG_VERSION
 *
 * SDF_VERSION is here to keep backwards compatibility. It was used
 * when the package version and protocol version were the same
 */
#define SDF_VERSION "1.6"

/* Package version number */
#define SDF_MAJOR_VERSION 8
#define SDF_MINOR_VERSION 3
#define SDF_PATCH_VERSION 0

#define SDF_MAJOR_VERSION_STR "8"
#define SDF_MINOR_VERSION_STR "3"
#define SDF_PATCH_VERSION_STR "0"

#define SDF_PKG_VERSION "8.3"
#define SDF_VERSION_FULL "8.3.0"
#define SDF_VERSION_NAME 
#define SDF_VERSION_NAMESPACE v8

#define SDF_VERSION_HEADER "Simulation Description Format (SDF), version 1.6\nCopyright (C) 2014 Open Source Robotics Foundation.\nReleased under the Apache 2 License.\nhttp://gazebosim.org/sdf\n\n"

/* #undef BUILD_TYPE_PROFILE */
/* #undef BUILD_TYPE_DEBUG */
/* #undef BUILD_TYPE_RELEASE */
/* #undef HAVE_URDFDOM */
#define USE_INTERNAL_URDF 1

#define SDF_SHARE_PATH "/usr/share/"
#define SDF_VERSION_PATH "/usr/share/sdformat8/"
